apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patient-service-ingress
spec:
  rules:
    - host: patient-service.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: patient-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appointment-service-ingress
spec:
  rules:
    - host: appointment-service.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appointment-service
                port:
                  number: 80
