name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - 'patient-service/**'
      - 'appointment-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image for Patient Service
        uses: docker/build-push-action@v2
        with:
          context: ./patient-service
          file: ./patient-service/Dockerfile
          push: true
          tags: 539935451710.dkr.ecr.us-west-2.amazonaws.com/patient-service:latest

      - name: Build and push Docker image for Appointment Service
        uses: docker/build-push-action@v2
        with:
          context: ./appointment-service
          file: ./appointment-service/Dockerfile
          push: true
          tags: 539935451710.dkr.ecr.us-west-2.amazonaws.com/appointment-service:latest
