# name: Docker Build and Push

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'patient-service/**'
#       - 'appointment-service/**'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to Amazon ECR
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: <your_ecr_repo>/patient-service:latest
